import { DropDownValue } from '../_types/customisedDropdown';

export const initialIndustryOption: DropDownValue = {
  id: 0,
  label: '',
  value: '',
};

export const initialCountryOption: DropDownValue = {
  id: 2,
  label: 'Australia',
  value: 'au',
  buttonLabel: 'AU Market',
};

export const initialPerformanceOption: DropDownValue = {
  id: 0,
  label: 'Market Cap High to Low',
  value: 'market-cap-large',
};

export const countryOptions: DropDownValue[] = [
  {
    id: 0,
    label: 'Global',
    value: 'global',
    buttonLabel: '🌎  Global',
  },
  {
    id: 1,
    label: 'United States',
    value: 'us',
    buttonLabel: 'US Market',
  },
  {
    id: 2,
    label: 'Australia',
    value: 'au',
    buttonLabel: 'AU Market',
  },
  {
    id: 3,
    label: 'United Kingdom',
    value: 'gb',
    buttonLabel: 'GB Market',
  },
  {
    id: 4,
    label: 'Canada',
    value: 'ca',
    buttonLabel: 'CA Market',
  },
  {
    id: 5,
    label: 'India',
    value: 'in',
    buttonLabel: 'IN Market',
  },
  {
    id: 6,
    label: 'China',
    value: 'cn',
    buttonLabel: 'CN Market',
  },
  {
    id: 7,
    label: 'Argentina',
    value: 'ar',
    buttonLabel: 'AR Market',
  },
  {
    id: 8,
    label: 'Austria',
    value: 'at',
    buttonLabel: 'AT Market',
  },
  {
    id: 9,
    label: 'Bahrain',
    value: 'bh',
    buttonLabel: 'BH Market',
  },
  {
    id: 10,
    label: 'Bangladesh',
    value: 'bd',
    buttonLabel: 'BD Market',
  },
  {
    id: 11,
    label: 'Belgium',
    value: 'be',
    buttonLabel: 'BE Market',
  },
  {
    id: 12,
    label: 'Bermuda',
    value: 'bm',
    buttonLabel: 'BM Market',
  },
  {
    id: 13,
    label: 'Botswana',
    value: 'bw',
    buttonLabel: 'BW Market',
  },
  {
    id: 14,
    label: 'Brazil',
    value: 'br',
    buttonLabel: 'BR Market',
  },
  {
    id: 15,
    label: 'Bulgaria',
    value: 'bg',
    buttonLabel: 'BG Market',
  },
  {
    id: 16,
    label: 'Chile',
    value: 'cl',
    buttonLabel: 'CL Market',
  },
  {
    id: 17,
    label: 'Colombia',
    value: 'co',
    buttonLabel: 'CO Market',
  },
  {
    id: 18,
    label: 'Croatia',
    value: 'hr',
    buttonLabel: 'HR Market',
  },
  {
    id: 19,
    label: 'Cyprus',
    value: 'cy',
    buttonLabel: 'CY Market',
  },
  {
    id: 20,
    label: 'Czech Republic',
    value: 'cz',
    buttonLabel: 'CZ Market',
  },
  {
    id: 21,
    label: 'Denmark',
    value: 'dk',
    buttonLabel: 'DK Market',
  },
  {
    id: 22,
    label: 'Egypt',
    value: 'eg',
    buttonLabel: 'EG Market',
  },
  {
    id: 23,
    label: 'Estonia',
    value: 'ee',
    buttonLabel: 'EE Market',
  },
  {
    id: 24,
    label: 'Finland',
    value: 'fi',
    buttonLabel: 'FI Market',
  },
  {
    id: 25,
    label: 'France',
    value: 'fr',
    buttonLabel: 'GB Market',
  },
  {
    id: 26,
    label: 'Germany',
    value: 'de',
    buttonLabel: 'DE Market',
  },
  {
    id: 27,
    label: 'Ghana',
    value: 'gh',
    buttonLabel: 'GH Market',
  },
  {
    id: 28,
    label: 'Greece',
    value: 'gr',
    buttonLabel: 'GR Market',
  },
  {
    id: 29,
    label: 'Hong Kong',
    value: 'hk',
    buttonLabel: 'HK Market',
  },
  {
    id: 30,
    label: 'Hungary',
    value: 'hu',
    buttonLabel: 'HU Market',
  },
  {
    id: 31,
    label: 'Iceland',
    value: 'is',
    buttonLabel: 'IS Market',
  },
  {
    id: 32,
    label: 'Indonesia',
    value: 'id',
    buttonLabel: 'ID Market',
  },
  {
    id: 33,
    label: 'Ireland',
    value: 'ie',
    buttonLabel: 'IE Market',
  },
  {
    id: 34,
    label: 'Israel',
    value: 'il',
    buttonLabel: 'IL Market',
  },
  {
    id: 35,
    label: 'Italy',
    value: 'it',
    buttonLabel: 'IT Market',
  },
  {
    id: 36,
    label: 'Ivory Coast',
    value: 'ci',
    buttonLabel: 'CI Market',
  },
  {
    id: 37,
    label: 'Jamaica',
    value: 'jm',
    buttonLabel: 'JM Market',
  },
  {
    id: 38,
    label: 'Japan',
    value: 'jp',
    buttonLabel: 'JP Market',
  },
  {
    id: 39,
    label: 'Jordan',
    value: 'jo',
    buttonLabel: 'JO Market',
  },
  {
    id: 40,
    label: 'Kenya',
    value: 'ke',
    buttonLabel: 'KE Market',
  },
  {
    id: 41,
    label: 'Kuwait',
    value: 'kw',
    buttonLabel: 'KW Market',
  },
  {
    id: 42,
    label: 'Latvia',
    value: 'lv',
    buttonLabel: 'LV Market',
  },
  {
    id: 43,
    label: 'Lithuania',
    value: 'lt',
    buttonLabel: 'LT Market',
  },

  {
    id: 45,
    label: 'Luxembourg',
    value: 'lu',
    buttonLabel: 'LU Market',
  },
  {
    id: 46,
    label: 'Malawi',
    value: 'mw',
    buttonLabel: 'MW Market',
  },
  {
    id: 47,
    label: 'Malaysia',
    value: 'my',
    buttonLabel: 'MY Market',
  },
  {
    id: 48,
    label: 'Malta',
    value: 'mt',
    buttonLabel: 'MT Market',
  },
  {
    id: 49,
    label: 'Mauritius',
    value: 'mu',
    buttonLabel: 'MU Market',
  },
  {
    id: 50,
    label: 'Mexico',
    value: 'mx',
    buttonLabel: 'MX Market',
  },
  {
    id: 51,
    label: 'Morocco',
    value: 'ma',
    buttonLabel: 'MA Market',
  },
  {
    id: 52,
    label: 'Namibia',
    value: 'na',
    buttonLabel: 'NA Market',
  },
  {
    id: 53,
    label: 'Netherlands',
    value: 'nl',
    buttonLabel: 'NL Market',
  },
  {
    id: 54,
    label: 'New Zealand',
    value: 'nz',
    buttonLabel: 'NZ Market',
  },
  {
    id: 55,
    label: 'Nigeria',
    value: 'ng',
    buttonLabel: 'NG Market',
  },
  {
    id: 56,
    label: 'Norway',
    value: 'no',
    buttonLabel: 'NO Market',
  },
  {
    id: 57,
    label: 'Oman',
    value: 'om',
    buttonLabel: 'OM Market',
  },
  {
    id: 58,
    label: 'Pakistan',
    value: 'pk',
    buttonLabel: 'PK Market',
  },
  {
    id: 59,
    label: 'Palestinian Authority',
    value: 'ps',
    buttonLabel: 'PS Market',
  },
  {
    id: 60,
    label: 'Peru',
    value: 'pe',
    buttonLabel: 'PE Market',
  },
  {
    id: 61,
    label: 'Philippines',
    value: 'ph',
    buttonLabel: 'PH Market',
  },
  {
    id: 62,
    label: 'Poland',
    value: 'pl',
    buttonLabel: 'PL Market',
  },
  {
    id: 63,
    label: 'Portugal',
    value: 'pt',
    buttonLabel: 'PT Market',
  },
  {
    id: 64,
    label: 'Qatar',
    value: 'qa',
    buttonLabel: 'QA Market',
  },
  {
    id: 65,
    label: 'Romania',
    value: 'ro',
    buttonLabel: 'RO Market',
  },
  {
    id: 66,
    label: 'Russia',
    value: 'ru',
    buttonLabel: 'RU Market',
  },
  {
    id: 67,
    label: 'Saudi Arabia',
    value: 'sa',
    buttonLabel: 'SA Market',
  },
  {
    id: 68,
    label: 'Serbia',
    value: 'rs',
    buttonLabel: 'RS Market',
  },
  {
    id: 69,
    label: 'Singapore',
    value: 'sg',
    buttonLabel: 'SG Market',
  },
  {
    id: 70,
    label: 'Slovakia',
    value: 'sk',
    buttonLabel: 'SK Market',
  },
  {
    id: 71,
    label: 'Slovenia',
    value: 'si',
    buttonLabel: 'SI Market',
  },
  {
    id: 72,
    label: 'South Africa',
    value: 'za',
    buttonLabel: 'ZA Market',
  },
  {
    id: 73,
    label: 'South Korea',
    value: 'kr',
    buttonLabel: 'KR Market',
  },
  {
    id: 74,
    label: 'Spain',
    value: 'es',
    buttonLabel: 'ES Market',
  },
  {
    id: 75,
    label: 'Sri Lanka',
    value: 'lk',
    buttonLabel: 'LK Market',
  },
  {
    id: 76,
    label: 'Sweden',
    value: 'se',
    buttonLabel: 'SE Market',
  },
  {
    id: 77,
    label: 'Switzerland',
    value: 'ch',
    buttonLabel: 'CH Market',
  },
  {
    id: 78,
    label: 'Taiwan',
    value: 'tw',
    buttonLabel: 'TW Market',
  },
  {
    id: 79,
    label: 'Tanzania',
    value: 'tz',
    buttonLabel: 'TZ Market',
  },
  {
    id: 80,
    label: 'Thailand',
    value: 'th',
    buttonLabel: 'TH Market',
  },
  {
    id: 81,
    label: 'Trinidad & Tobago',
    value: 'tt',
    buttonLabel: 'TT Market',
  },
  {
    id: 82,
    label: 'Tunisia',
    value: 'tn',
    buttonLabel: 'TN Market',
  },
  {
    id: 83,
    label: 'Turkey',
    value: 'tr',
    buttonLabel: 'TR Market',
  },
  {
    id: 84,
    label: 'Uganda',
    value: 'ug',
    buttonLabel: 'UG Market',
  },
  {
    id: 85,
    label: 'Ukraine',
    value: 'ua',
    buttonLabel: 'UA Market',
  },
  {
    id: 86,
    label: 'United Arab Emirates',
    value: 'ae',
    buttonLabel: 'AE Market',
  },
  {
    id: 87,
    label: 'Venezuela',
    value: 've',
    buttonLabel: 'VE Market',
  },
  {
    id: 88,
    label: 'Vietname',
    value: 'vn',
    buttonLabel: 'VN Market',
  },
  {
    id: 89,
    label: 'Zambia',
    value: 'zm',
    buttonLabel: 'ZM Market',
  },
  {
    id: 90,
    label: 'Zimbabwe',
    value: 'zw',
    buttonLabel: 'ZW Market',
  },
];

export const industryOptions: DropDownValue[] = [
  {
    id: 0,
    label: 'Any',
    value: '',
  },
  {
    id: 4010000,
    label: 'Automobiles',
    value: 'automobiles',
  },
  {
    id: 7010000,
    label: 'Banks',
    value: 'banks',
  },
  {
    id: 3010000,
    label: 'Capital Goods',
    value: 'capital-goods',
  },
  {
    id: 3100000,
    label: 'Commercial Services',
    value: 'commercial-services',
  },
  {
    id: 4100000,
    label: 'Consumer Durables',
    value: 'consumer-durables',
  },
  {
    id: 5010000,
    label: 'Consumer Retailing',
    value: 'consumer-retailing',
  },
  {
    id: 4200000,
    label: 'Consumer Services',
    value: 'consumer-services',
  },
  {
    id: 7100000,
    label: 'Diversified Financials',
    value: 'diversified-financials',
  },
  {
    id: 1010000,
    label: 'Energy',
    value: 'energy',
  },
  {
    id: 5100000,
    label: 'Food, Beverage & Tobacco',
    value: 'food-beverage-tobacco',
  },
  {
    id: 6010000,
    label: 'Healthcare',
    value: 'healthcare',
  },
  {
    id: 5200000,
    label: 'Household',
    value: 'household',
  },
  {
    id: 7200000,
    label: 'Insurance',
    value: 'insurance',
  },
  {
    id: 2010000,
    label: 'Materials',
    value: 'materials',
  },
  {
    id: 4300000,
    label: 'Media',
    value: 'media',
  },
  {
    id: 6100000,
    label: 'Pharmaceuticals & Biotech',
    value: 'pharmaceuticals-biotech',
  },
  {
    id: 7300000,
    label: 'Real Estate',
    value: 'real-estate',
  },
  {
    id: 9622303,
    label: 'Real Estate Management and Development',
    value: 'real-estate-management-and-development',
  },
  {
    id: 4400000,
    label: 'Retail',
    value: 'retail',
  },
  {
    id: 8200000,
    label: 'Semiconductors',
    value: 'semiconductors',
  },
  {
    id: 8010000,
    label: 'Software',
    value: 'software',
  },
  {
    id: 8100000,
    label: 'Tech',
    value: 'tech',
  },
  {
    id: 9010000,
    label: 'Telecom',
    value: 'telecom',
  },
  {
    id: 3200000,
    label: 'Transportation',
    value: 'transportation',
  },
  {
    id: 9510000,
    label: 'Utilities',
    value: 'utilities',
  },
];

export const performanceFilterOptions: DropDownValue[] = [
  {
    id: 0,
    label: 'Market Cap High to Low',
    value: 'market-cap-large',
  },
  {
    id: 1,
    label: 'Market Cap Low to High',
    value: 'market-cap-small',
  },
  {
    id: 2,
    label: 'Top Gainers Today',
    value: 'top-gainers',
  },
  {
    id: 3,
    label: 'Biggest Losers Today',
    value: 'biggest-losers',
  },
  {
    id: 4,
    label: 'Growth',
    value: 'growth',
  },
  {
    id: 5,
    label: 'Dividend Yield',
    value: 'dividend-yield-high',
  },
];
